title: gregdoros' blog
description: Uczymy się pythona & django

url: http://gregdoros.github.io
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Główna
   url: /index.html
 - title: Artykuły      # Dopisujemy nazwę linka
   url: /articles       # Dopisujemy ścieżkę
 - title: O mnie
   url: /about
 - title: Kontakt
   url: /contact


social:
   github: brianmaierjr
   twitter: brianmaierjr
   facebook: brianmaierjr
   email: brimaidesigns@gmail.com

google_analytics: "UA-58263416-1"
